
<?php

$title = 'Alumnos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin', array('action'=>'agregar-alumnos'));?>">Add new alumno</a>
</p>
<p>
   <a href="./admin/calificaciones">ir a calificaciones</a>

    
</p>
<p>
    <a href="/admin/cursos">Ir a cursos</a>
</p>
<p>
    <a href="/admin/profesores">ir a profesores</a>
</p>
<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($alumnos as $alumno) : ?>
<tr>
    <td><?php echo $this->escapeHtml($alumno->idAlumno);?></td>
    <td><?php echo $this->escapeHtml($alumno->nombres);?></td>
    <td>
        <a href="<?php echo $this->url('admin',
            array('action'=>'editar', 'id' => $alumno->idAlumno));?>">Edit</a>
        <a href="<?php echo $this->url('admin',
            array('action'=>'borrar', 'id' => $alumno->idAlumno));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>