<?php
$title = 'Inscribir Alumno';
 $this->headTitle($title);
 
include_once ("layout-header.phtml");
?>
		

<div class="row">

<?php
include_once ("aside-menu.phtml");
?>
	 
		 <div class="main-content  col-xs-12 col-sm-6 col-md-7">
		 

 <h2><?php echo $this->escapeHtml($title); ?></h2>
 <?php
 $form->setAttribute('action', $this->url('alumnos', array('action' => 'agregar')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('idAlumno'));
 echo $this->formRow($form->get('aPaterno'));
 echo '<br>';
 echo $this->formRow($form->get('aMaterno'));
 echo '<br>';
 echo $this->formRow($form->get('nombres'));
 echo '<br>';
 echo $this->formRow($form->get('mail'));
 echo '<br>';
 echo $this->formRow($form->get('tipoEstudiante'));
 echo '<br>';
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();

?>
</div>
		 
</div>