<div class="aside-menu well col-xs-12 col-md-5 col-sm-6">
	<div class="col-xs-12 col-md-12">
		<div class="thumbnail">
			<img data-src="js/bootstrap.min.js" src=<?php echo $this->basePath() .'/img/background-alumnos.png'?>>
		</div>
	</div>

	<div class="section-menu btn-group col-xs-12 col-md-12">
		<a href="#" class="btn btn-Alumnos btn-block" role="button">Inscribir</a>
		<a href="#" class="btn btn-Alumnos btn-block" role="button">Actualizar Datos</a>
		<a href="#" class="btn btn-Alumnos btn-block" role="button">Borrar</a>
	</div>

</div>