<?php
include_once ("layout-header.phtml");
?>
		

<div class="row">

<?php
include_once ("aside-menu.phtml");
?>
	 
		 <div class="main-content  col-xs-12 col-sm-6 col-md-7">
		 
<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($alumnos as $alumno) : ?>
<tr>
    <td><?php echo $this -> escapeHtml($alumno -> idAlumno); ?></td>
    <td><?php echo $this -> escapeHtml($alumno -> nombres); ?></td>
    <td>
    	<!--
        <a href="<?php echo $this->url('alumnos',
            array('action'=>'editar', 'id' => $alumno->idAlumno));?>">Edit</a>
        <a href="<?php echo $this->url('alumnos',
            array('action'=>'borrar', 'id' => $alumno->idAlumno));?>">Delete</a>
           -->
    </td>
</tr>
<?php endforeach; ?>
</table>
</div>
		 
</div>