<?php
$mytitle = 'Borrar';
$this->headTitle($mytitle);
 
include_once ("layout-header.phtml");
?>

<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
		<div class="thumbnail">	
			<img data-src="js/bootstrap.min.js" src=<?php echo $this->basePath() .'/img/background-alumnos.png'?>>
		</div>
		
		<input type="submit" name="del" value="Borrar" form="delete" role="button" class="btn my-btn-Alumnos btn-block" />
		<a class="btn my-btn-Alumnos btn-block" role="button"
			href="<?php echo $this -> url('alumnos', array('action' => 'index')); ?>">Cancelar</a>
	</div>

</div>
	 
<div class="main-content col-sm-offset-1  col-xs-12 col-sm-6 col-md-7"> 

 <h2><?php echo $this->escapeHtml($mytitle); ?></h2>
 <p>
 	Estas seguro de querer borrar al alumno 
 </p>
 <p> 
 	<strong>
     '<?php echo $this -> escapeHtml($alumno -> nombres),' ',
	 			 $this -> escapeHtml($alumno -> aPaterno),' ', 
	 			 $this -> escapeHtml($alumno -> aMaterno);?>' 
	</strong>? 
</p>
 <?php
 $url = $this->url('alumnos', array(
     'action' => 'borrar',
     'id'     => $this->id,
 ));
 ?>
 <form name="delete" action="<?php echo $url; ?>" method="POST">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $alumno->idAlumno; ?>" />
     <input class="btn btn-default" type="submit" name="del" value="Si" />
     <input class="btn btn-default" type="submit" name="del" value="No" />
 </div>
 </form>
		 
</div>