<?php
include_once ("layout-header.phtml");
include_once ("aside-menu.phtml");
?>
<div class="main-content  col-xs-12 col-sm-7 col-md-8">
		 <h1><?php echo $this->escapeHtml($title); ?></h1>
		 
		<?php 
		
		$flash = $this->flashMessenger();
 		$flash->setMessageOpenFormat(
 		'<div%s>
 			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
 				&times;
 			</button>
    	<ul><li><strong>')
     				->setMessageSeparatorString('</strong></li><li><strong>')
     				->setMessageCloseString('</strong></li></ul></div>');
 echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<table class="table">
<tr>
    <th>id</th>
    <th>Nombre Completo</th>
    <th>Mail</th>
    <th>Tipo estudiante</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($alumnos as $alumno) : ?>
<tr>
    
     <td><?php echo $this -> escapeHtml($alumno -> idAlumno); ?></td>
	 <td><?php echo $this -> escapeHtml($alumno -> nombres),' ',
	 				$this -> escapeHtml($alumno -> aPaterno),' ', 
	 				$this -> escapeHtml($alumno -> aMaterno);
	 				 ?>
	 </td>
    <td><?php echo $this -> escapeHtml($alumno -> mail); ?></td>
    <td><?php echo $this -> escapeHtml($alumno -> tipoEstudiante); ?></td>
    <td>
    	
        <a href="<?php echo $this -> url('alumnos', array('action' => 'editar', 'id' => $alumno -> idAlumno)); ?>">Editar</a>
        <a href="<?php echo $this -> url('alumnos', array('action' => 'borrar', 'id' => $alumno -> idAlumno)); ?>">Borrar</a>
           
    </td>
</tr>
<?php endforeach; ?>
</table>
</div>
<?php $this->headScript()->captureStart() ?>
			function activeSection() {
				document.getElementById('aside-menu').className = "index well col-xs-12 col-md-4 col-sm-5";
			}

			window.addEventListener('load', activeSection, false);
		<?php $this->headScript()->captureEnd() ?>
		
