<?php
$mytitle = 'Mostrar';
$this->headTitle($mytitle);

include_once ("layout-header.phtml");
?>
<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
		<a class="btn my-btn-Alumnos btn-block" role="button"
			href="<?php echo $this -> url('alumnos', array('action' => 'editar', 'id' => $alumno -> idAlumno)); ?>">Editar Datos</a>
		<a class="btn my-btn-Alumnos btn-block" role="button"
			href="<?php echo $this -> url('alumnos', array('action' => 'borrar', 'id' => $alumno -> idAlumno)); ?>">Borrar</a>
		<a class="btn my-btn-Alumnos btn-block" role="button"
			href="<?php echo $this -> url('alumnos', array('action' => 'buscar')); ?>">Buscar</a>
		<a  class="btn my-btn-Alumnos btn-block" role="button" 
			href="<?php echo $this -> url('alumnos', array('action' => 'inscripcion')); ?>">Inscribir</a>
	</div>
</div>

<div class="main-content  col-xs-12 col-sm-7 col-md-8">
	<div class="col-sm-offset-1  col-xs-12 col-sm-6 col-md-7">
		<h1><?php echo $this->escapeHtml($mytitle); ?></h1>
		<table class="table table-striped">
	<thead>
<tr>
    <th>Columna</th>
    <th>Dato</th>
</tr>
</thead>
<tbody>
	<tr>
		<td>ID</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> idAlumno); ?>
	
		</td>
	</tr>
	
	<tr>
		<td>Nombre(s)</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> nombres); ?>
	
		</td>
	</tr>
	<tr>
		<td>Apellido<br>Paterno</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> aPaterno); ?> 
	
		</td>
	</tr>
	<tr>
		<<td>Apellido<br>Materno</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> aMaterno); ?>
    
		</td>
	</tr>
	<tr>
		<td>Correo<br>Electrónico</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> mail); ?>
		</td>
	</tr>
	<tr>
		<td>Tipo de <br>
			estudiante
		</td>
		<td>
			 <?php echo $this -> escapeHtml($alumno -> tipoEstudiante); ?>
    
		</td>
	</tr>
	<tr>
		<td>Telefonos</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> telefonos); ?>
		</td>
	</tr>
	<tr>
		<td>CURP</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> curp); ?>
		</td>
	</tr>
	<tr>
		<td>Folio Examen</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> folioExamen); ?>
		</td>
	</tr>
	<tr>
		<td>Tutor</td>
		<td>
			<?php echo $this -> escapeHtml($alumno -> nombreTutor); ?>
		</td>
	</tr>
 	<tr>
		<td>
			 <a href="<?php echo $this -> url('alumnos', array('action' => 'editar', 'id' => $alumno -> idAlumno)); ?>">Editar</a>
		</td>
		<td>
			<a href="<?php echo $this -> url('alumnos', array('action' => 'borrar', 'id' => $alumno -> idAlumno)); ?>">Borrar</a>
		</td>
	</tr>

</tbody>
</table>          
</div>
</div>