<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
	&nbsp;
	</div>

</div>
<div class="main-content col-sm-offset-1  col-xs-12 col-sm-6 col-md-7"> 

 <h2><?php echo $this->escapeHtml('Ingreso'); ?></h2>
	
        <?php
        $form = $this->form;
        $form->prepare();
         
        echo $this->form()->openTag($form);
        // Despliega el campo "Nombre de Usuario", con su label y sus posibles errores
        echo $this->formLabel($form->get('username'));
        echo $this->formText($form->get('username'));
        echo $this->formElementErrors($form->get('username'));
         
        // Similar al campo superior
        echo $this->formLabel($form->get('pass'));
        echo $this->formPassword($form->get('pass'));
        echo $this->formElementErrors($form->get('pass'));
 
        // Despliega el elemento CSRF como hidden        
        echo $this->formHidden($form->get('csrfcheck'));
        echo $this->formElementErrors($form->get('csrfcheck'));
         
        // Muestra el boton
        echo $this->formSubmit($form->get('submit'));
         
        echo $this->form()->closeTag();
        ?>
    </div>
