<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
	&nbsp;
	</div>

</div>
<div class="main-content col-sm-offset-1  col-xs-12 col-sm-6 col-md-7"> 

 <h2><?php echo $this->escapeHtml('Ingreso'); ?></h2>
 <?php
	$flash = $this -> flashMessenger();
	$flash -> setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
&times;
</button>
<ul><li><strong>') 
		-> setMessageSeparatorString('</strong></li><li><strong>') 
		-> setMessageCloseString('</strong></li></ul></div>');
	echo $flash -> render('error', 	 array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash -> render('info', 	 array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash -> render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash -> render('success', array('alert', 'alert-dismissable', 'alert-success'));
	?>
	
        <?php
        $form = $this->form;
        $form->prepare();
         
        echo $this->form()->openTag($form);
        // Despliega el campo "Nombre de Usuario", con su label y sus posibles errores
        echo $this->formLabel($form->get('identity'));
        echo $this->formText($form->get('identity'));
        echo $this->formElementErrors($form->get('identity'));
         
        // Similar al campo superior
        echo $this->formLabel($form->get('credential'));
        echo $this->formPassword($form->get('credential'));
        echo $this->formElementErrors($form->get('credential'));
 
        // Despliega el elemento CSRF como hidden        
        echo $this->formHidden($form->get('csrfcheck'));
        echo $this->formElementErrors($form->get('csrfcheck'));
         
        // Muestra el boton
        echo $this->formSubmit($form->get('submit'));
         
        echo $this->form()->closeTag();
        ?>
    </div>
