
<?php

$title = 'Alumnos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin', array('Controller'=>'alumnos', 'action'=>'add'));?>">Add new alumno</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($alumnos as $alumno) : ?>
<tr>
    <td><?php echo $this->escapeHtml($alumno->idAlumno);?></td>
    <td><?php echo $this->escapeHtml($alumno->nombres);?></td>
    <td>
        <a href="<?php echo $this->url('admin',
            array('Controller'=>'alumnos', 'action'=>'edit', 'id' => $alumno->id));?>">Edit</a>
        <a href="<?php echo $this->url('admin',
            array('Controller'=>'alumnos', 'action'=>'delete', 'id' => $alumno->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>