<?php
$mytitle = 'Agregar';
$this->headTitle($mytitle);
 
include_once ("layout-header.phtml");
include_once ("aside-menu.phtml");
?>

<div class="main-content col-sm-offset-1  col-xs-12 col-sm-6 col-md-7"> 

 <h2><?php echo $this->escapeHtml($mytitle); ?></h2>
 <?php
 $form->setAttribute('class','form-horizontal');
 $form->setAttribute('role','form');
 $form->setAttribute('method', 'POST');
 $form->setAttribute('action', $this->url('profesores', array('action' => 'agregar')));
 $formLabel = $this->plugin('formLabel');
 
 
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('idProfesor'));
 
 ?>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php echo $this->formLabel($form->get('nombres')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('nombres')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php echo $this->formLabel($form->get('aPaterno')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('aPaterno')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php echo $this->formLabel($form->get('aMaterno')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('aMaterno')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php echo $this->formLabel($form->get('mail')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('mail')); ?>
    </div>
  </div>
  
  <div class="form-group">
   
    <div class="col-sm-offset-2 col-sm-7">
      <?php echo $this->formSubmit($form->get('submit')); ?>
      <a  class="btn btn-default" role="button" href="<?php echo $this -> url('profesores'); ?>">Cancelar</a>
    </div>
  </div>
  
  
 <?php echo $this->form()->closeTag(); ?>
 <?php
 
?>
</div>
		 