<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
		<div class="thumbnail">	
			<img data-src="js/bootstrap.min.js" src=<?php echo $this->basePath() .'/img/background-profesores.png'?>>
		</div>
		<a  class="btn my-btn-Profesores btn-block" role="button" 
			href="<?php echo $this -> url('profesores', array('action' => 'agregar')); ?>">Agregar</a>
		<a class="btn my-btn-Profesores btn-block" role="button"
			href="<?php echo $this -> url('profesores', array('action' => 'todos')); ?>">Listar Todos</a>
	</div>

</div>

