<?php
include_once ("layout-header.phtml");
?>
		
<div id="aside-menu" class="index well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
		<div class="thumbnail">	
			<img data-src="js/bootstrap.min.js" src=<?php echo $this->basePath() .'/img/background-profesores.png'?>>
		</div>
		<a  class="btn my-btn-Profesores btn-block" role="button" 
			href="<?php echo $this -> url('profesores', array('action' => 'agregar')); ?>">Agregar</a>
		<a class="btn my-btn-Profesores btn-block" role="button"
			href="<?php echo $this -> url('profesores', array('action' => 'editar')); ?>">Editar Datos</a>
		<a class="btn my-btn-Profesores btn-block" role="button"
			href="<?php echo $this -> url('profesores', array('action' => 'borrar')); ?>">Borrar</a>
	</div>

</div>
	 
		 <div class="main-content  col-xs-12 col-sm-6 col-md-7">
		 
<div class="table-responsive">
<table class="table table-striped table-condensed">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($profesores as $profesor) : ?>
<tr>
    <td><?php echo $this -> escapeHtml($profesor-> idProfesor); ?></td>
    <td><?php echo $this -> escapeHtml($profesor -> nombres); ?></td>
    <td>
    	<!--
        <a href="<?php echo $this->url('alumnos',
            array('action'=>'editar', 'id' => $alumno->idAlumno));?>">Edit</a>
        <a href="<?php echo $this->url('alumnos',
            array('action'=>'borrar', 'id' => $alumno->idAlumno));?>">Delete</a>
           -->
    </td>
</tr>
<?php endforeach; ?>
</table>
</div>

</div>
