<?php
$mytitle = 'Buscar';
$this->headTitle($mytitle);

include_once ("layout-header.phtml");
?>
<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
		<div class="thumbnail">	
			<img data-src="js/bootstrap.min.js" src=<?php echo $this->basePath() .'/img/background-profesores.png'?>>
		</div>
		<a  class="btn my-btn-Profesores btn-block" role="button" 
			href="<?php echo $this -> url('profesores', array('action' => 'agregar')); ?>">Agregar</a>
		<a class="btn my-btn-Profesores btn-block" role="button"
			href="<?php echo $this -> url('profesores', array('action' => 'todos')); ?>">Listar Todos</a>
	</div>

</div>

<div class="main-content  col-xs-12 col-sm-7 col-md-8">
	<div class="col-sm-offset-1  col-xs-12 col-sm-6 col-md-7">
		 <h1><?php echo $this->escapeHtml($mytitle); ?> <?php //echo $this->escapeHtml($title); ?></h1>
		 
		<?php 
		
		$flash = $this->flashMessenger();
 		$flash->setMessageOpenFormat(
 		'<div%s>
 			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
 				&times;
 			</button>
    	<ul><li><strong>')
     				->setMessageSeparatorString('</strong></li><li><strong>')
     				->setMessageCloseString('</strong></li></ul></div>');
 echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>


	<?php
	
 $form->setAttribute('class','form-horizontal');
 $form->setAttribute('role','form');
 $form->setAttribute('method', 'POST');
 $form->setAttribute('action', $this->url('profesores', array('action' => 'buscar')));
 $formLabel = $this->plugin('formLabel');
 
 
 $form->prepare();

 echo $this->form()->openTag($form);
 
 echo $this->formHidden($form->get('idProfesor'));
 echo $this->formHidden($form->get('mail'));
 echo $this->formHidden($form->get('telefonos'));
 
 
 ?>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php /*echo $formLabel->openTag() . $form->get('nombres')->getOption('label'), $formLabel->closeTag();*/?>
    <?php echo $this->formLabel($form->get('nombres')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('nombres')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php echo $this->formLabel($form->get('aPaterno')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('aPaterno')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
     <?php echo $this->formLabel($form->get('aMaterno')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('aMaterno')); ?>
    </div>
  </div>

 <div class="form-group">
  	<div class="col-sm-2 control-label">
      <?php 'Correo electrónico' ?>
            <!--echo $this->formLabel($form->get('mail'));-->
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('mail')); ?>
    </div>
  </div>
 
  <div class="form-group">
   
    <div class="col-sm-offset-2 col-sm-7">
      <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
  </div>
  
  
 <?php echo $this->form()->closeTag(); ?>
</div>

<?php if($profesores!=NULL) { ?>
	
<div class="table-responsive">
<table class="table table-striped table-condensed">
<!--
<table class="table table-hover table-condensed">
-->		
	
	<thead>
<tr>
  <!--  <th>id</th> -->
    <th>Nombre Completo</th>
    <th>Mail</th>
    <th>Teléfonos</th>
    <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($profesores as $profesor) : ?>
<tr>
    
    <!-- <td><?php echo $this -> escapeHtml($profesor -> idProfesor); ?></td> -->
    
	 <td>
	 <strong>	
	 	<a href="<?php echo $this -> url('profesores', array('action' => 'mostrar', 'id' => $profesor -> idProfesor)); ?>">
	 	<?php echo $this -> escapeHtml($profesor -> nombres),'<br>',
	 				$this -> escapeHtml($profesor -> aPaterno),'<br>', 
	 				$this -> escapeHtml($profesor -> aMaterno);
	 				 ?>
	 	</a>
	 </strong>				 
	 </td>
    <td><?php echo $this -> escapeHtml($profesor -> mail); ?></td>
    <td><?php echo $this -> escapeHtml($profesor -> telefonos); ?></td>
    <td>
    	
        <a href="<?php echo $this -> url('profesores', array('action' => 'editar', 'id' => $profesor -> idProfesor)); ?>">Editar</a>
        <a href="<?php echo $this -> url('profesores', array('action' => 'borrar', 'id' => $profesor -> idProfesor)); ?>">Borrar</a>
           
    </td>
</tr>
<?php endforeach; 
}
?>
</tbody>
</table>
</div>

