<?php
$mytitle = 'Editar';
$this->headTitle($mytitle);
 
include_once ("layout-header.phtml");

?>

<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
		<div class="thumbnail">	
			<img data-src="js/bootstrap.min.js" src=<?php echo $this->basePath() .'/img/background-profesores.png'?>>
		</div>
		
		<input type="submit" name="submit" id="submitbutton" class="btn my-btn-Profesores btn-block" 
			value="Editar" form="profesor" role="button"  />
	
		<a class="btn my-btn-Profesores btn-block" role="button"
			href="<?php echo $this -> url('profesores', array('action' => 'index')); ?>">Cancelar</a>
	</div>

</div>
	 
<div class="main-content col-sm-offset-1  col-xs-12 col-sm-6 col-md-7"> 

 <h2><?php echo $this->escapeHtml($mytitle); ?></h2>
 <?php
 $form->setAttribute('class','form-horizontal');
 $form->setAttribute('role','form');
 $form->setAttribute('method', 'POST');
 $form->setAttribute('action', $this->url('profesores', array('action' => 'editar','id' => $this->id,)));
 $formLabel = $this->plugin('formLabel');
 
 
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('idProfesor'));
 
 ?>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php /*echo $formLabel->openTag() . $form->get('nombres')->getOption('label'), $formLabel->closeTag();*/?>
    <?php echo $this->formLabel($form->get('nombres')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('nombres')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php echo $this->formLabel($form->get('aPaterno')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('aPaterno')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
     <?php echo $this->formLabel($form->get('aMaterno')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('aMaterno')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
     <?php echo $this->formLabel($form->get('mail')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('mail')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
      <?php echo $this->formLabel($form->get('mail')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formSelect($form->get('mail')); ?>
    </div>
  </div>
 <div class="form-group">
  	<div class="col-sm-2 control-label">
     <?php echo $this->formLabel($form->get('telefonos')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('telefonos')); ?>
    </div>
  </div>
 
  <div class="form-group">
   
   
    <div class="col-sm-offset-2 col-sm-7">
      <?php echo $this->formSubmit($form->get('submit')); ?>
      <a  class="btn btn-default" role="button" 
			href="<?php echo $this -> url('profesores'); ?>">Cancelar</a>
    </div>
  </div>
  
  
 <?php echo $this->form()->closeTag(); ?>

		 
</div>