<?php
include_once ("layout-header.phtml");
include_once ("aside-menu.phtml");
?>
	 
		  <div class="main-content  col-xs-12 col-sm-7 col-md-8">
<h1><?php echo $this->escapeHtml('Profesores'); ?></h1>
		 
<table class="table">
<tr>
     <th>idProfesor</th>
	<th>aPaterno</th>
	<th>aMaterno</th>
	<th>nombres</th>
    <th>mail</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($profesores as $profesor) : ?>
<tr>
    <td><?php echo $this -> escapeHtml($profesor -> idProfesor); ?></td>
	<td><?php echo $this -> escapeHtml($profesor -> aPaterno); ?></td>
	<td><?php echo $this -> escapeHtml($profesor -> aMaterno); ?></td>
	<td><?php echo $this -> escapeHtml($profesor -> nombres); ?></td>
    <td><?php echo $this -> escapeHtml($profesor -> mail); ?></td>	
    <td>
    	
        <a href="<?php echo $this -> url('profesores', array('action' => 'editar', 'id' => $profesor -> idCalificaciones)); ?>">Edit</a>
        <a href="<?php echo $this -> url('profesores', array('action' => 'borrar', 'id' => $profesor -> idCalificaciones)); ?>">Delete</a>
           
    </td>
</tr>
<?php endforeach; ?>
</table>
</div>
<?php $this->headScript()->captureStart() ?>
			function activeSection() {
				document.getElementById('aside-menu').className = "index well col-xs-12 col-md-4 col-sm-5";
			}

			window.addEventListener('load', activeSection, false);
		<?php $this->headScript()->captureEnd() ?>