		<!-- Le styles -->
		<?php 
			echo $this->headLink()
						->prependStylesheet($this->basePath() . '/css/blue-bootstrap.min.css')	
		?>
		
				
		<?php
		$title = 'Profesores';
		$this -> headTitle($title);
		?>

	
	<div class="row">
		 <div class="aside-menu well col-xs-6 col-md-5" style="">
		 	<header>
		 		<h2><?php echo $this -> escapeHtml($title); ?></h2>
		 	</header>
		 </div>
  		<div class="main-content col-xs-12 col-sm-6 col-md-7">
  				Action "index", controller "Profesores", module "Profesores".
  		</div>
  	</div>
	

