<?php
$mytitle = 'Todos los Profesores';
$this->headTitle($mytitle);

include_once ("layout-header.phtml");
?>
<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">

    <div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
        <div class="thumbnail">	
            <img data-src="js/bootstrap.min.js" src=<?php echo $this->basePath() . '/img/background-profesores.png' ?>>
        </div>
        <a class="btn my-btn-Profesores btn-block" role="button"
           href="<?php echo $this->url('profesores', array('action' => 'buscar')); ?>">Buscar</a>
        <a  class="btn my-btn-Profesores btn-block" role="button" 
            href="<?php echo $this->url('profesores', array('action' => 'agregar')); ?>">Agregar</a>
    </div>

</div>

<div class="main-content  col-xs-12 col-sm-7 col-md-8">
    <h1><?php echo $this->escapeHtml($mytitle); ?></h1>

    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat(
                    '<div%s>
 			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
 				&times;
 			</button>
    	<ul><li><strong>')
            ->setMessageSeparatorString('</strong></li><li><strong>')
            ->setMessageCloseString('</strong></li></ul></div>');
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    ?>

    <div class="table-responsive">
        <table class="table table-striped table-condensed">
            <thead>
                <tr>
                    <th>Nombre Completo</th>
                    <th>Mail</th>
                    <th>Teléfonos</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($profesores as $profesor) : ?>
                    <tr>

    <!--   <td><?php echo $this->escapeHtml($profesor->idProfesor); ?></td> -->
                        <td>
                            <strong>
                                <a href="<?php echo $this->url('profesores', array('action' => 'mostrar', 'id' => $profesor->idProfesor)); ?>">
                                    <?php
                                    echo $this->escapeHtml($profesor->nombres), '<br>',
                                    $this->escapeHtml($profesor->aPaterno), '<br>',
                                    $this->escapeHtml($profesor->aMaterno);
                                    ?>
                                </a>
                            </strong>			 
                        </td>
                        <td><?php echo $this->escapeHtml($profesor->mail); ?></td>
                        <td><?php echo $this->escapeHtml($profesor->telefonos); ?></td>
                        <td>

                            <a class="btn btn-primary-Profesores btn-block" role="button" href="<?php echo $this->url('profesores', array('action' => 'editar', 'id' => $profesor->idProfesor)); ?>">Editar</a>
                            <a class="btn btn-primary-Profesores btn-block" role="button" href="<?php echo $this->url('profesores', array('action' => 'borrar', 'id' => $profesor->idProfesor)); ?>">Borrar</a>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

</div>