<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
 
return array(
    'modules' => array(
		/*
		'ZendDeveloperTools',
		'BjyProfiler', 
		 */
        'Application',
        'Alumnos',
        'Calificaciones',
        'Cursos',
        'Profesores',
        'Login'
        ),

    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),

        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
        
		
		
		'config_cache_key' => 'app_config',
		'module_map_cache_key' => 'module_map',
		'check_dependencies' => FALSE,
		'cache_dir' => 'data/cache/',   
    ),
);
