<div id="aside-menu" class="well col-xs-12 col-md-4 col-sm-5">
	
	<div class="section-menu btn-group col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
	&nbsp;
	</div>

</div>

<div class="main-content col-sm-offset-1  col-xs-12 col-sm-6 col-md-7"> 

 <h2><?php echo $this->escapeHtml('Ingreso'); ?></h2>
 <?php
	$flash = $this -> flashMessenger();
	$flash -> setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
&times;
</button>
<ul><li><strong>') 
		-> setMessageSeparatorString('</strong></li><li><strong>') 
		-> setMessageCloseString('</strong></li></ul></div>');
	echo $flash -> render('error', 	 array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash -> render('info', 	 array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash -> render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash -> render('success', array('alert', 'alert-dismissable', 'alert-success'));
	?>
	
       
        
        <?php
 $form->setAttribute('class','form-horizontal');
 $form->setAttribute('role','form');
 $form->setAttribute('method', 'POST');
 //$form->setAttribute('action', $this->url('', array('action' => 'editar','id' => $this->id,)));
 $formLabel = $this->plugin('formLabel');
 
 
 $form->prepare();

 echo $this->form()->openTag($form);
 
 ?>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php /*echo $formLabel->openTag() . $form->get('nombres')->getOption('label'), $formLabel->closeTag();*/?>
    <?php echo $this->formLabel($form->get('username')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('username')); ?>
    </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2 control-label">
    <?php echo $this->formLabel($form->get('pass')); ?>
    </div>
    <div class="col-sm-7">
      <?php echo $this->formInput($form->get('pass')); ?>
    </div>
  </div>
  
     <?php 	echo $this->formHidden($form->get('csrfcheck')); 
     		echo $this->formElementErrors($form->get('csrfcheck'));?>
   
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-7">
      <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
  </div>
  
  
 <?php echo $this->form()->closeTag(); ?>
        
        
    </div>
